services:
  - type: web
    name: budget-planner
    env: python
    buildCommand: "./build.sh"
    startCommand: "python main.py"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: REFRESH_SECRET_KEY
        generateValue: true
      - key: PORT
        value: 10000
  
databases:
  - name: budget-planner-db
    databaseName: budget_planner
    user: budget_user
